name: Build EXE

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Cài đặt các dependencies từ requirements.txt

    - name: Build EXE
      run: pyinstaller --onefile --windowed --add-data "templates;templates" --add-data "static;static" app.py

    - name: Upload EXE
      uses: actions/upload-artifact@v2
      with:
        name: application
        path: dist/app.exe
